name: Link PR to Notion (Reusable)
on:
  workflow_call:
    inputs:
      pr_body:
        type: string
        required: true
      pr_title:
        type: string
        required: true
      pr_url:
        type: string
        required: true
      pr_number:
        type: string
        required: true
    secrets:
      NOTION_TOKEN:
        required: true

jobs:
  link-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: your-org/.github  # ← 自分のorg名に変更
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install @notionhq/client
      - name: Link PR to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PR_BODY: ${{ inputs.pr_body }}
          PR_TITLE: ${{ inputs.pr_title }}
          PR_URL: ${{ inputs.pr_url }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: node .github/scripts/link-notion.js
